version: '3.5'


services:
  app:
    image: ${ORG:-ej}/app:${TAG:-latest}
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: local
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USERNAME=${USER:-user}
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    env_file:
      - ./config.env
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ENVIRONMENT=local
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_DB_URL=psql://ej:ej@postgres:5432/table
    volumes:
      - ../:/app/
    command: db -m run


  postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=table
      - POSTGRES_USER=ej
      - POSTGRES_PASSWORD=ej
    volumes:
      - db_ej_dev:/var/lib/postgresql/data/


volumes:
  db_ej_dev:
