services:
  - docker:dind

stages:
  - test
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  DJANGO_PRODUCTION_IMAGE: "besouro/ej-server:production"
  DJANGO_STAGING_IMAGE: "besouro/ej-server:staging"
  DJANGO_DEVELOP_IMAGE: "besouro/ej-server:develop"
  BACKEND_PRODUCTION_IMAGE: "besouro/api:production"
  BACKEND_STAGING_IMAGE: "besouro/api:staging"
  DJANGO_TEST_ENV: "./besouro/docker/develop/env/django.test.env"
  POSTGRES_TEST_ENV: "./besouro/docker/develop/env/postgres.test.env"

.builder: &builder
  image: docker
  before_script:
    - docker pull $DJANGO_PRODUCTION_IMAGE || true
    - docker build --cache-from $DJANGO_PRODUCTION_IMAGE --build-arg VOLATILE_DEPENDENCIES_STRATEGY=$(date +%s) -t $DJANGO_PRODUCTION_IMAGE -f ./besouro/docker/production/django/Dockerfile .
  tags:
    - docker

#
# Testing
#

test:
  << : *builder
  stage: test
  script:
    - docker build -t $DJANGO_DEVELOP_IMAGE -f ./besouro/docker/develop/django/Dockerfile .
    - docker run -d --env-file=$POSTGRES_TEST_ENV --name=postgres postgres:9.6
    - docker run --env-file=$DJANGO_TEST_ENV --env-file=$POSTGRES_TEST_ENV --link=postgres:postgres $DJANGO_DEVELOP_IMAGE /test.sh

#
# Pushing images to registry
#

push:staging:nginx:
  << : *builder
  stage: push
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build -t $BACKEND_STAGING_IMAGE -f ./besouro/docker/production/nginx/staging.Dockerfile .
    - docker push $BACKEND_STAGING_IMAGE
  only:
    - master

push:staging:django:
  << : *builder
  stage: push
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker push $DJANGO_STAGING_IMAGE
  only:
    - master

push:production:nginx:
  << : *builder
  stage: push
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build -t $BACKEND_PRODUCTION_IMAGE -f ./besouro/docker/production/nginx/staging.Dockerfile .
    - docker push $BACKEND_PRODUCTION_IMAGE
  only:
    - master

push:production:django:
  << : *builder
  stage: push
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker push $DJANGO_PRODUCTION_IMAGE
  only:
    - master

#
# Kubernetes Upgrade
#

# FIXME: Set Kubernetes Jobs
# .deployer: &deployer
#   image:
#   script:
#     - TODO
#   tags:
#     - docker

# TODO: Production deployment unavailable
# deploy:master:
#   << : *deployer
#   stage: deploy
#   environment: staging
#   only:
#     - develop

# deploy:latest:
#   << : *deployer
#   stage: deploy
#   environment: production
#   only:
#     - master
