stages:
    - prepare
    - check_code_style
    - run_tests
    - build
    - deploy

variables:
    GITLAB_EJ_TOKEN: "gitlab+deploy-token-533883:51xTbvyHGmEfeZZUxUct"

install_dependencies:
    stage: prepare
    image:
        name: python:3.7
        pull_policy: if-not-present
    script:
        - apt update && apt install -y bash git curl
    tags:
        - osf

check_style:
    stage: check_code_style
    image:
        name: python:3.7
        pull_policy: if-not-present
    before_script:
        - pip install black==22.3.0
    script:
        - black --check .

run_tests:
    stage: run_tests
    image:
        name: python:3.7
        pull_policy: if-not-present
    script:
        - /bin/sh -c 'git clone -b $CI_COMMIT_REF_NAME https://$GITLAB_EJ_TOKEN@gitlab.com/pencillabs/ej/ej-application.git'
        - cd ej-application
        - pip install poetry
        - poetry install --only ci
        - poetry run inv test
    tags:
        - osf

build_dev_image:
    stage: deploy
    image:
        name: docker
        pull_policy: if-not-present
    script:
        - apk update && apk add git
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl build ej -e dev -b develop -c prod --no-cache --push
    only:
        refs:
            - develop
    tags:
        - osf

build_prod_image:
    stage: build
    image:
        name: docker
        pull_policy: if-not-present
    script:
        - apk update && apk add git
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl build ej -e dev -b prod -c prod --no-cache --push
    only:
        refs:
            - prod
    tags:
        - osf

deploy_to_dev:
    stage: deploy
    image:
        name: docker
        pull_policy: if-not-present
    script:
        - apk update && apk add git
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl deploy ej -e dev -c prod
    only:
        refs:
            - develop
    tags:
        - osf
