image: python:3.7
stages:
    - prepare
    - style
    - test
    - deploy

variables:
    GITLAB_INFRA_TOKEN: 'gitlab+deploy-token-1093201:zQBUtxqVTA5PyWUyGyEC'
    GITLAB_EJ_TOKEN: 'gitlab+deploy-token-533883:51xTbvyHGmEfeZZUxUct'

install_dependencies:
    stage: prepare
    script:
        - apt update && apt install -y bash git curl
    tags:
        - osf

check_style:
  before_script:
    - pip install black==22.3.0
  stage: style
  script:
    - black --check .

run_tests:
    stage: test
    script:
        - /bin/sh -c 'git clone -b $CI_COMMIT_REF_NAME https://$GITLAB_EJ_TOKEN@gitlab.com/pencillabs/ej/ej-application.git'
        - cd ej-application
        - pip install poetry
        - poetry run pip install 'setuptools==61.2.0'
        - poetry install
        - poetry run inv test
    tags:
        - osf

deploy_to_dev:
    stage: deploy
    script:
        - /bin/sh -c 'git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git'
        - cd core
        - bin/pencilctl build ej -e dev -b develop -c prod --no-cache --push
    only:
        refs:
            - develop
    tags:
        - osf

deploy_to_prod:
    stage: deploy
    script:
        - /bin/sh -c 'git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git'
        - cd core
        - bin/pencilctl build ej -e prod -b prod -c prod --no-cache --push
    only:
        refs:
            - prod
    tags:
        - osf
