stages:
  - style
  - linter
  - unit tests
  - build
    # - deploy
    # - e2e tests

.pipeline-rules:
  r1: &push_dev $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'develop'
  r2: &job_build $JOB == 'build'
  r3: &merge_request $CI_PIPELINE_SOURCE == 'merge_request_event'

variables:
  GITLAB_EJ_TOKEN: "gitlab+deploy-token-533883:51xTbvyHGmEfeZZUxUct"
  EJ_THEME: "ej"
  SERVICE: "ej"
  ENVIRONMENT:
    value: "production"
    description: "Ambiente no qual o JOB será executado."
    options:
      - "none"
      - "production"
  JOB:
    value: "none"
    description: "JOB desejado."
    options:
      - "build"
      - "none"
      - "unit tests"
  #   - "deploy"

.kaniko-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - test -n "$CONTEXT" || { echo "CONTEXT não definido"; exit 1; }
    - test -n "$EJ_THEME" || { echo "EJ_THEME não definido"; exit 1; }
    - test -n "$DOCKERFILE" || { echo "DOCKERFILE não definido"; exit 1; }
    - test -f "$DOCKERFILE" || { echo "Dockerfile não encontrado - $DOCKERFILE"; exit 1; }
    - export IMAGE_NAME="$CI_REGISTRY_IMAGE/$SERVICE:$IMAGE_TAG"
    - export CI_REGISTRY_IMAGE="$CI_REGISTRY_IMAGE"
    - export CI_REGISTRY_USER="$CI_REGISTRY_USER"
    - export CI_REGISTRY_PASSWORD="$CI_REGISTRY_PASSWORD"
    - echo "Autenticando"
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "auth": "$(printf '%s:%s' "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64 -w0)"
          }
        }
      }
      EOF
    - echo "Building and pushing $IMAGE_NAME"
    - |
      /kaniko/executor \
        --context "$CONTEXT" \
        --dockerfile "$DOCKERFILE" \
        --destination "$IMAGE_NAME" \
        --build-arg VERSION="$IMAGE_TAG" --build-arg EJ_THEME="$EJ_THEME" \
        --log-timestamp

docker-build:
  extends: .kaniko-build
  environment:
    name: "$ENVIRONMENT"
    action: prepare
  variables:
    CONTEXT: .
    DOCKERFILE: docker/Dockerfile-prod
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA # TODO: Taggear imagem baseado na release
    FF_TIMESTAMPS: "1"
  rules:
    - if: *push_dev
    - if: *job_build

black:
  stage: style
  image:
    name: python:3.9.19-slim-bookworm
    pull_policy: if-not-present
  before_script:
    - /bin/bash -c "pip install black==22.12.0"
  script:
    - /bin/bash -c "black --check ."
  tags:
    - av-ci-runner
  rules:
    - if: *merge_request

ruff:
  stage: linter
  image:
    name: python:3.9.19-slim-bookworm
    pull_policy: if-not-present
  before_script:
    - /bin/bash -c "pip install ruff==0.3.7"
  script:
    - /bin/bash -c "ruff check"
  tags:
    - av-ci-runner
  rules:
    - if: *merge_request

pytest:
  stage: unit tests
  image:
    name: python:3.9.19-slim-bookworm
    pull_policy: if-not-present
  before_script:
    - apt-get update && apt-get install curl libpq-dev gcc g++ libjpeg-dev zlib1g-dev git -y
  script:
    - cd /builds/pencillabs/ej/ej-application
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install --with main,dev --no-root
    - poetry run inv docs
    - poetry run inv test
  tags:
    - av-ci-runner
  rules:
    - if: *merge_request
    - if: *job_build
