image: python:3.7
stages:
    - prepare
    - style
    - test
    - deploy

install_dependencies:
    stage: prepare
    script:
        - apt update && apt install -y bash git curl
    tags:
        - osf

check_style:
  before_script:
    - pip install black==21.5b2
  stage: style
  script:
    - black --check .

run_tests:
    stage: test
    script:
        - /bin/sh -c 'git clone -b $CI_COMMIT_REF_NAME https://gitlab+deploy-token-154801:r9Qas_TYJeyzC1fmdpsD@gitlab.com/pencillabs/ej/ej-server.git'
        - cd ej-server
        - pip install poetry
        - poetry install
        - poetry run inv test
    tags:
        - osf

deploy_to_dev:
    stage: deploy
    script:
        - /bin/sh -c 'git clone -b stable --depth=1 https://gitlab+deploy-token-155341:xWz-bGxYnvTLcZCzsHEG@gitlab.com/pencillabs/infraestructure/core.git'
        - cd core
        - bin/pencilctl build ej -e dev -b develop -c prod --no-cache --push
    only:
        refs:
            - develop
    tags:
        - osf

deploy_to_prod:
    stage: deploy
    script:
        - /bin/sh -c 'git clone -b stable --depth=1 https://gitlab+deploy-token-155341:xWz-bGxYnvTLcZCzsHEG@gitlab.com/pencillabs/infraestructure/core.git'
        - cd core
        - bin/pencilctl build ej -e prod -b prod -c prod --no-cache --push
    only:
        refs:
            - prod
    tags:
        - osf
