stages:
    - style
    - tests
    - build
    - deploy

variables:
    GITLAB_EJ_TOKEN: "gitlab+deploy-token-533883:51xTbvyHGmEfeZZUxUct"

black:
    stage: style
    image:
        name: python:3.8.18-slim-bullseye
        pull_policy: if-not-present
    before_script:
        - /bin/bash -c "pip install black==22.3.0"
    script:
        - /bin/bash -c "black --check ."
    tags:
        - k8s

pytest:
    stage: tests
    image:
        name: python:3.8.18-slim-bullseye
        pull_policy: if-not-present
    before_script:
        - apt update && apt install git libpq-dev gcc  -y
    script:
        - cd /builds/pencillabs/ej/ej-application
        - pip install poetry
        - poetry install --with main,dev --no-root
        - poetry run inv docs
        - poetry run inv test
    tags:
        - k8s

e2e:
    stage: tests
    image: cypress/base:18.16.0
    script:
        - cd /builds/pencillabs/ej/ej-application/e2e
        - npm i
        - npx cypress run --config baseUrl=https://ejplatform.pencillabs.com.br
    tags:
        - k8s

build_dev_image:
    stage: build
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add bash py3-pip
        - docker info
    script:
        - cd /builds/pencillabs/ej/ej-application
        - python3 -m venv /tmp/venv &&  . /tmp/venv/bin/activate && pip install invoke django-environ
        - . /tmp/venv/bin/activate && inv docker-build --tag ${CI_COMMIT_SHA} --registry registry.pencillabs.tec.br --no-cache
        - . /tmp/venv/bin/activate && inv docker-push --tag ${CI_COMMIT_SHA} --registry registry.pencillabs.tec.br
    only:
        refs:
            - k8s-pipeline
    tags:
        - k8s

deploy_dev_image:
    stage: deploy
    image:
        name: python:3.8.18-slim-bullseye
        pull_policy: if-not-present
    before_script:
        - apt update && apt install git curl -y
    script:
        - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        - helm version
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/pencillabs/infraestructure/helm-charts.git
        - cd helm-charts
        - helm upgrade ej-homolog ej -f ej/values-homolog.yaml --set server.image.tag="${CI_COMMIT_SHA}" --install --kubeconfig $K8S_CONFIG
    only:
        refs:
            - k8s-pipeline
    tags:
        - k8s

build_prod_image:
    stage: build
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add git
    script:
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl build ej -e prod -b prod -c prod --no-cache --push
    only:
        refs:
            - prod
    tags:
        - k8s

deploy_to_dev:
    stage: deploy
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add git
    script:
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl deploy ej -e dev -c prod
    only:
        refs:
            - develop
    tags:
        - k8s
