stages:
    - style
    - tests
    - build
    - deploy

variables:
    GITLAB_EJ_TOKEN: "gitlab+deploy-token-533883:51xTbvyHGmEfeZZUxUct"

black:
    stage: style
    image:
        name: python:3.8.18-slim-bullseye
        pull_policy: if-not-present
    before_script:
        - /bin/bash -c "pip install black==22.3.0"
    script:
        - /bin/bash -c "black --check ."
    tags:
        - osf

pytest:
    stage: tests
    image:
        name: python:3.8.18-slim-bullseye
        pull_policy: if-not-present
    before_script:
        - apt update && apt install git -y
    script:
        - cd /builds/pencillabs/ej/ej-application
        - pip install poetry
        - poetry install --only ci
        - poetry run inv test
    tags:
        - osf

e2e:
    stage: tests
    image: cypress/base:18.16.0
    script:
        - cd /builds/pencillabs/ej/ej-application/e2e
        - npm i
        - npx cypress run --config baseUrl=https://ejplatform.pencillabs.com.br
    tags:
        - osf

build_dev_image:
    stage: build
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add git
    script:
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl build ej -e dev -b develop -c prod --no-cache --push
    only:
        refs:
            - develop
    tags:
        - osf

build_prod_image:
    stage: build
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add git
    script:
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl build ej -e prod -b prod -c prod --no-cache --push
    only:
        refs:
            - prod
    tags:
        - osf

deploy_to_dev:
    stage: deploy
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add git
    script:
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl deploy ej -e dev -c prod
    only:
        refs:
            - develop
    tags:
        - osf
