stages:
    - check_code_style
    - run_tests
    - build_docker_images
    - deploy_environments

variables:
    GITLAB_EJ_TOKEN: "gitlab+deploy-token-533883:51xTbvyHGmEfeZZUxUct"

check_style:
    stage: check_code_style
    image:
        name: python:3.7-slim-buster
        pull_policy: if-not-present
    before_script:
        - pip install black==22.3.0
    script:
        - black --check .
    tags:
        - osf

run_tests:
    stage: run_tests
    image:
        name: python:3.7-slim-buster
        pull_policy: if-not-present
    before_script:
        - apt update && apt install git -y
    script:
        - /bin/sh -c 'git clone -b $CI_COMMIT_REF_NAME https://$GITLAB_EJ_TOKEN@gitlab.com/pencillabs/ej/ej-application.git'
        - cd ej-application
        - pip install poetry
        - poetry install --only ci
        - poetry run inv test
    tags:
        - osf

build_dev_image:
    stage: build_docker_images
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add git -y
    script:
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl build ej -e dev -b develop -c prod --no-cache --push
    only:
        refs:
            - develop
    tags:
        - osf

build_prod_image:
    stage: build_docker_images
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add git -y
    script:
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl build ej -e prod -b prod -c prod --no-cache --push
    only:
        refs:
            - prod
    tags:
        - osf

deploy_to_dev:
    stage: deploy_environments
    image:
        name: docker
        pull_policy: if-not-present
    before_script:
        - apk update && apk add git -y
    script:
        - git clone -b stable --depth=1 https://$GITLAB_INFRA_TOKEN@gitlab.com/pencillabs/infraestructure/core.git
        - cd core
        - bin/pencilctl deploy ej -e dev -c prod
    only:
        refs:
            - develop
    tags:
        - osf
