image: python:3.7
stages:
    - prepare
    - test
    - deploy
install_dependencies:
    stage: prepare
    script:
        - apt update && apt install -y bash git
    tags:
        - osf

run_tests:
    stage: test
    script:
        - /bin/sh -c 'git clone -b $CI_COMMIT_REF_NAME https://gitlab+deploy-token-154801:r9Qas_TYJeyzC1fmdpsD@gitlab.com/pencillabs/ej/ej-server.git'
        - cd ej-server
        - pip install markupsafe toolz
        - pip install sidekick
        - pip install -r etc/requirements-ci.txt
        - inv test
    tags:
        - osf

deploy_to_dev:
    stage: deploy
    script:
        - /bin/sh -c 'git clone -b stable --depth=1 https://gitlab+deploy-token-155341:xWz-bGxYnvTLcZCzsHEG@gitlab.com/pencillabs/infraestructure/core.git'
        - cd core
        # TODO: remove this after issue https://gitlab.com/pencillabs/infraestructure/core/-/issues/227 is done
        - 'sed -i "s#current: local#current: prod#" pencilctl/config.yml'
        - bin/pencilctl build ej -i server -e dev -b develop --no-cache && bin/pencilctl push ej -i server -e dev -b develop
    only:
        refs:
            - develop

deploy_to_prod:
    stage: deploy
    script:
        - /bin/sh -c 'git clone -b stable --depth=1 https://gitlab+deploy-token-155341:xWz-bGxYnvTLcZCzsHEG@gitlab.com/pencillabs/infraestructure/core.git'
        - cd core
        # TODO: remove this after issue https://gitlab.com/pencillabs/infraestructure/core/-/issues/227 is done
        - 'sed -i "s#current: local#current: prod#" pencilctl/config.yml'
        - bin/pencilctl build ej -i server -e prod -b prod --no-cache && bin/pencilctl push ej -i server -e prod -b prod
    only:
        refs:
            - prod
