stages:
  - test

job:
  stage: test
  script: rm -rf core
  script: git clone https://gitlab+deploy-token-75921:VCK1rszjsSE-jSJuDS3o@gitlab.com/pencillabs/infraestructure/core.git -b go_cli
  script: cd core && bin/pencil build ej -b $CI_COMMIT_REF_NAME
  script: cd core && bin/pencil build ej -i db -b $CI_COMMIT_REF_NAME
  script: cd core && bin/pencil test ej -b $CI_COMMIT_REF_NAME
