os: linux
dist: trusty
sudo: required
env:
  global:
    - CC_TEST_REPORTER_ID=774db8cce863050fe5bc219651c79d338521ca894b66ee3df3b9a2eb6a27f3e7
language: python
python:
  - '3.6'
install:
  - ./configure.sh
  - pip install invoke
  - pip install -r etc/requirements/production.txt
  - inv update-deps db db-assets db-fake
script:
  - pytest
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
