language: python
cache: pip
sudo: false


env:
  global:
    - CC_TEST_REPORTER_ID=774db8cce863050fe5bc219651c79d338521ca894b66ee3df3b9a2eb6a27f3e7


matrix:
  include:
   - env: TOXENV=py37-sqlite
     python: '3.7'
   - env: TOXENV=py36-sqlite
     python: '3.6'


install:
  - pip install invoke
  - inv configure --silent


script:
  - inv test


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build


after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
