# This docker-compose file is not designed to run
# Usage: Build & Push

version: '3.5'

services:
  ej-server:
    image: besouro/ej-server:production
    build:
      context: ../../../../
      dockerfile: ./docker/production/django/Dockerfile
      args:
        VOLATILE_DEPENDECIES_STRATEGY: ${VOLATILE_DEPS_STRATEGY}
      cache_from:
        - ejplatform/ej-server:master
