# This docker-compose file is not designed to run services
# Usage:
#   sudo docker-compose -f build.yml build
#   sudo docker-compose -f build.yml push

version: "3.6"

services:
  ej-server:
    image: besouro/ej-server:production
    build:
      context: ../../../
      dockerfile: ./besouro/docker/production/Dockerfile
      cache_from:
        - besouro/ej-server:production
