version: '3.5'


services:
  nginx:
    image: ${ORG:-ej}/nginx:latest
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    volumes:
      - media_files:/usr/share/nginx/html/media
      - static_files:/usr/share/nginx/html/static
    ports:
      - 80:80
    depends_on:
      - web
    links:
      - web


  web:
    image: ${ORG:-ej}/web:${TAG:-latest}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: deploy
      args:
        - THEME=${EJ_THEME:-default}
    restart: always
    links:
      - postgres
    env_file:
      - ./config.env
    volumes:
      - media_files:/app/local/media/
      - static_files:/app/local/static/


  postgres:
    image: postgres:10-alpine
    restart: always
    env_file:
      - ./config.env
    volumes:
      - db_ej:/var/lib/postgresql/data


volumes:
  db_ej:
  media_files:
  static_files:
