version: '3.5'


services:
  web:
    image: ej/web:dev
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-dev
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    env_file:
      - ./env/django.env
      - ./env/postgres.env
      - ./env/local.env
    environment:
      - DJANGO_ENVIRONMENT=local
    volumes:
      - ../:/app/
    command: db -m run

  postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - ej_dev_db_data:/var/lib/postgresql/data/

volumes:
  ej_dev_db_data:
