version: '3.5'


services:

  # The Rocket.Chat container. It doesn't require much preparation at this stage.
  # Integration with EJ is done at later stage using Rocket.Chat administrative
  # UI.
  rocketchat:
    image: rocketchat/rocket.chat:${ROCKETCHAT_VERSION:-0.74.3}
    restart: always
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat
      PORT: '3000'
      ROOT_URL: http://${EJ_ROCKETCHAT_URL:-rocketchat}:3000
    links:
      - mongo:mongo
    ports:
      - 3000:3000/tcp
      - 41101:41101


  # The MONGO_DB database. You can drop this container if you want to use an
  # external MongoDB instance. Just change the MONGO_URL environment variable
  # to the correct value in the rocketchat section above.
  mongo:
    image: ej/mongo
    build:
      context: .
      dockerfile: Dockerfile-mongo
    volumes:
      - db_rocketchat:/data/db
      - ./scripts:/scripts/
    ports:
      - 27017:27017/tcp
    command:
      - mongod
      - --smallfiles
      - --oplogSize
      - '128'


volumes:
  db_rocketchat:

