version: '3.5'


services:
  web:
    image: ejplatform/web:dev
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - UID=${UID:-1000}
    ports:
      - 8000:8000
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ./env/django.env
      - ./env/postgres.env
      - ./env/email.env
      - ${ENVFILE:-./env/override.env}
    environment:
      - DJANGO_ENVIRONMENT=local
    volumes:
      - ../:/app/
    entrypoint: tail -f /dev/null

  postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - dev_db_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379


volumes:
  dev_db_data:
