version: '3.5'


services:
  nginx:
    image: ejplatform/nginx:latest
    volumes:
      - media_files:/usr/share/nginx/html/media
      - static_files:/usr/share/nginx/html/static
      - docs:/usr/share/nginx/html/docs
    ports:
      - 80:80
    depends_on:
      - web
    links:
      - web

  web:
    image: ejplatform/web:latest
    restart: always
    links:
      - postgres
      - redis
    env_file:
      - ./env/django.env
      - ./env/postgres.env
      - ./env/deploy.env
      - ./env/email.env
    volumes:
      - media_files:/app/local/media/
      - static_files:/app/local/static/
      - docs:/app/build/docs/
      - nginx_conf:/etc/nginx/conf.d/
    command: clean db -m db-assets sass collect gunicorn

  postgres:
    image: postgres:10-alpine
    restart: always
    env_file:
      - ./env/deploy.env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always


volumes:
  db_data:
  media_files:
  static_files:
  nginx_conf:
  docs:
