version: '3'
services:
  db:
    build:
      context: ./db
      args:
        - API_TAG=${API_TAG}
  api:
    build:
      context: ./api
      args:
        - API_TAG=${API_TAG}
    ports:
    - "5000:8000"
    links:
      - db
