# Generated by Django 5.2 on 2026-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ej_conversations",
            "0040_alter_conversation_anonymous_votes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="anonymous_votes",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Define how many anonymous votes each participant can cast.",
                verbose_name="Number of anonymous votes",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(
                help_text="A brief description about this conversation. It will be used internally to create URL identifiers.",
                max_length=255,
                verbose_name="Title",
            ),
        ),
    ]
