apiVersion: v1
kind: Service
metadata:
  name: besouro-postgres
  labels:
    app: besouro
spec:
  ports:
    - port: 5432
  selector:
    app: besouro
    tier: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besouro-postgres-pvc
  labels:
    app: besouro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: besouro-postgres
  labels:
    app: besouro
spec:
  selector:
    matchLabels:
      app: besouro
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: besouro
        tier: postgres
    spec:
      containers:
      - image: postgres:9.6
        name: postgres
        imagePullPolicy: "Always"
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: besouro-postgres
              key: db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: besouro-postgres
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: besouro-postgres
              key: user
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data-storage
        persistentVolumeClaim:
          claimName: besouro-postgres-pvc
