# Local docker-compose file
version: '3.5'

networks:
  ej:
    name: ej

volumes:
  db_data: {}

services:
  django: &django
    image: besouro/ej-server:develop
    build:
      context: ../../../
      dockerfile: ./besouro/docker/develop/django/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./env/django.env
      - ./env/postgres.env
    links:
      - postgres
    networks:
      - ej
    ports:
      - 8000:8000
    volumes:
      - ../../../:/app
    working_dir: /app

  postgres:
    image: postgres:9.6
    env_file:
      - ./env/postgres.env
    networks:
      - ej
    volumes:
      - db_data:/var/lib/postgresql/data
